### ISSUE TITLE
Templating plugin not found

### ISSUE THREAD

**Issue by stackflow** [Tapad/sbt-marathon#7]
Trying to create .json file for marathon from templating plugin
This string to ./project/plugins.sbt was added:
addSbtPlugin("com.tapad.sbt" % "sbt-marathon-templating" % "0.2.0")
Also ./build.sbt was edited:
enablePlugins(DockerPlugin, MarathonPlugin, TemplatingPlugin)

After that sbt command are failed with a message:
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	:: com.tapad.sbt#sbt-marathon-templating;0.2.0: not found
[warn] 
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies
[warn]      exist with the requested attributes.
[warn] 		com.tapad.sbt:sbt-marathon-templating:0.2.0 (scalaVersion=2.12, sbtVersion=1.0)
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.tapad.sbt:sbt-marathon-templating:0.2.0 (scalaVersion=2.12, sbtVersion=1.0)

scalaVersion = "2.12.4"
sbt.version = 1.0.2

Is it a bug or my mistake?

**Comment by jeffreyolchovy** [comment]
No, it is was bug. Addressed in #8. Thanks for bringing this to my attention! Fix version will be 0.2.1, should be published and available in a few minutes.

**Comment by jeffreyolchovy** [comment]
0.2.1 is now available on [bintray](https://dl.bintray.com/sbt/sbt-plugin-releases/com.tapad.sbt/sbt-marathon-templating/scala_2.12/sbt_1.0/0.2.1/).

**Comment by stackflow** [comment]
I have changed ./project/plugins.sbt:
addSbtPlugin("com.tapad.sbt" % "sbt-marathon" % "0.2.1")
addSbtPlugin("com.tapad.sbt" % "sbt-marathon-templating" % "0.2.1")

But now I have another error:
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.tapad.sbt#marathon-util_2.12;0.2.1: not found
[warn] 	:: com.tapad.sbt#marathon-templating-lib_2.12;0.2.1: not found

**Comment by jeffreyolchovy** [comment]
Ah, interesting. Those artifacts are published maven-style and should be available on Maven Central (unlike the actual sbt plugin artifacts which are published ivy-style to the sbt-plugins bintray repo). Let me make sure there is not an issue between the sync between the project's repo and Maven Central. Thanks for your patience.

**Comment by jeffreyolchovy** [comment]
Ok, just re-synced with Maven Central:
```
{"status":"Successfully synced and closed repo.","messages":["Sync finished successfully."]}
```

It may take a few minutes for this to propagate.

---

As an alternative course of action, if you don't want to wait for them to become available from Central, you should be able to add our bintray repo as a resolver in your project:

I believe the following should work (untested):

In build.sbt:
```
resolvers += Resolver.bintrayRepo("tapad-oss", "maven")
```

And if the plugin artifacts were not resolving, in project/plugins.sbt:
```
resolvers += Resolver.bintrayIvyRepo("tapad-oss", "sbt-plugins")
```

I will spend some time doing some local testing with the above declarations and update the README.md with the proper instructions as it seems like the syncing of the artifacts to the publicly available channels has a pretty bad turn-around time and is more fragile than I'd like.

**Comment by jeffreyolchovy** [comment]
And in the time it took me to write that, they have made it to Central (http://repo1.maven.org/maven2/com/tapad/sbt/marathon-templating-lib_2.12/0.2.1/) :)

**Comment by stackflow** [comment]
Thank you for your work!
It works perfectly!
